version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    command: puma -C config/puma.rb
    image: railsapp:test

  sidekiq:
    volumes_from:
      - app
    depends_on:
      - 'postgres'
      - 'redis'
    command: sidekiq -C config/sidekiq.yml.erb

  cable:
    volumes_from:
      - app
    depends_on:
      - 'redis'
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'

volumes:
  redis:
  postgres:
